version: "3"
services:
  db:
    image: "postgres:latest"
    container_name: "postgres"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_DB: "Orders"
    volumes:
      - "./db/:/var/lib/postgresql/data"
  azurite:
    image: "mcr.microsoft.com/azure-storage/azurite"
    container_name: "azurite"
    restart: "always"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
